setwd("/Users/ben_cosgo/Working_directory")
library("tidyverse")
data <- read.csv("~/Working_directory/clean_diamond_data.csv")
attach(data)
table(data$color)
table(data$clarity)
table(data$cut)
library(plyr)
library(dplyr)
data$cutscore <- revalue(data$cut, c("Good"="0", "Very Good"="1", "Ideal"="2", "Astor Ideal"="3"))
data$clarityscore <- revalue(data$clarity, c("SI2"="0", "SI1"="1", "VS2"="2", "VS1"="3","VVS2"="4", "VVS1"="5", "IF"="6", "FL"="7"))
data$cutscore <- as.numeric(cutscore)
data$clarityscore <- as.numeric(clarityscore)
plot(cutscore~clarityscore)
